server:
  port: 8082
spring:
  application:
    name: repair-service
  mongodb:
    uri: ${SPRING_MONGODB_URI:mongodb://mongoadmin:123456@localhost:27017/gara_business_db?authSource=admin}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
