server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://mysql:3306/gara_core_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: gara_user
    password: garapassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/